apiVersion: v1
kind: DeploymentConfig
metadata:
  name: webserver-staging
  namespace: vshn-demoapp1
  selfLink: /oapi/v1/namespaces/vshn-demoapp1/deploymentconfigs/webserver-staging
  uid: 7a15e420-0274-11e7-a314-fa163ec9e279
  creationTimestamp: '2017-03-06T13:54:54Z'
  labels:
    app: webserver-staging
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources:
  replicas: 1
  test: false
  selector:
    app: webserver-staging
    deploymentconfig: webserver-staging
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webserver-staging
        deploymentconfig: webserver-staging
      annotations:
        openshift.io/container.webserver-staging.image.entrypoint: '["nginx","-g","daemon off;"]'
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        -
          name: webserver-staging
          image: '172.30.1.1:5000/vshn-demoapp1/webserver@sha256:208ea2d1268ade8bdf79370281e5658bc1be4705b065821bab7633004ccf1008'
          ports:
            -
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
