apiVersion: v1
kind: Route
metadata:
  name: webserver-staging
  namespace: vshn-demoapp1
  selfLink: /oapi/v1/namespaces/vshn-demoapp1/routes/webserver-staging
  uid: 961e042e-0276-11e7-8841-fa163e3ec73a
  creationTimestamp: '2017-03-06T14:10:00Z'
  labels:
    app: webserver-staging
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: webserver-staging-vshn-demoapp1.appuioapp.ch
  to:
    kind: Service
    name: webserver-staging
    weight: 100
  port:
    targetPort: 9000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
