apiVersion: v1
kind: Service
metadata:
  name: webserver-staging
  namespace: vshn-demoapp1
  selfLink: /api/v1/namespaces/vshn-demoapp1/services/webserver-staging
  uid: 7a1f8911-0274-11e7-a2d1-fa163ed95dac
  creationTimestamp: '2017-03-06T13:54:54Z'
  labels:
    app: webserver-staging
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  ports:
    -
      name: 9000-tcp
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: webserver-staging
    deploymentconfig: webserver-staging
  portalIP: 172.30.215.173
  clusterIP: 172.30.215.173
  type: ClusterIP
  sessionAffinity: None
