stages:
    - test
    - compile
    - build

cache:
    key: "$CI_PROJECT_ID"
    paths:
        - .yarn
        - node_modules/

test:
    stage: test
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-folder=".yarn"
        # - yarn test
    artifacts:
        expire_in: "5min"
        paths:
            - ".yarn"

compile:
    stage: compile
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-folder=".yarn"
        - yarn build
    artifacts:
        expire_in: "5min"
        paths:
            - "build"
    only:
        - master

build:
    stage: build
    image: registry.vshn.net/roland.schlaefli/docs_runner_oc
    services:
        - docker:dind
    script:
        - oc login $KUBE_URL --token=$KUBE_TOKEN
        - docker login -u serviceaccount -p `oc whoami -t` $OC_REGISTRY_URL
        # - docker pull $OC_REGISTRY_IMAGE:latest
        # - docker build --cache-from $OC_REGISTRY_IMAGE:latest -t $OC_REGISTRY_IMAGE:latest .
        - docker build . -t $OC_REGISTRY_IMAGE:latest
        - docker push $OC_REGISTRY_IMAGE:latest
    only:
        - master
    tags:
        - dockerbuild
    variables:
        OC_REGISTRY_URL: "registry.appuio.ch"
        OC_REGISTRY_IMAGE: "$OC_REGISTRY_URL/$KUBE_NAMESPACE/docs_example_webserver"
    environment: staging