stages:
    - test
    - compile
    - build

cache:
    key: "$CI_PROJECT_ID"
    paths:
        - .yarn
        - node_modules/
        - build/

test:
    stage: test
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-folder=".yarn"
        # - yarn test
    artifacts:
        expire_in: "5min"
        paths:
            - ".yarn"

compile:
    stage: compile
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-folder=".yarn"
        - yarn build
    artifacts:
        expire_in: "5min"
        paths:
            - "build"

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE
        - docker build --cache-from $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE
    tags:
        - dockerbuild