stages:
    - test
    - compile
    - build

test:
    stage: test
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install
        - yarn test

compile:
    stage: compile
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install
        - yarn build

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
    tags:
        - dockerbuild