stages:
    - test
    - compile
    - build

before_script:
    - yarn config set cache-folder cache

test:
    stage: test
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install
        - yarn test
        - yarn cache ls
        - yarn cache dir
    artifacts:
        expire_in: "5min"
        paths:
            - "cache"
    cache:
        paths:
            - "cache"

compile:
    stage: compile
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install
        - yarn build
    artifacts:
        expire_in: "5min"
        paths:
            - "build"
    cache:
        paths:
            - "cache"

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
    tags:
        - dockerbuild