stages:
    - test
    - compile
    - build

cache:
    key: "$CI_PROJECT_ID"
    paths:
        - .yarn
        - node_modules/
        - build/

before_script:
    - yarn config set cache-folder ".yarn"

test:
    stage: test
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install
        - yarn test --cache-folder=".yarn-test"
    artifacts:
        expire_in: "5min"
        paths:
            - ".yarn"

compile:
    stage: compile
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install
        - yarn build
    artifacts:
        expire_in: "5min"
        paths:
            - "build"

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
    tags:
        - dockerbuild