stages:
  - build
  - deploy-staging
  - deploy-preprod
  - deploy-prod

variables:
  CLUSTER_IP_STAGING: 172.30.215.173
  CLUSTER_IP_PREPROD: 172.30.29.25
  CLUSTER_IP_PROD: 172.30.31.200
  NODE_VERSION: 6.10-alpine
  OC_REGISTRY_URL: registry.appuio.ch
  OC_REGISTRY_IMAGE: $OC_REGISTRY_URL/$KUBE_NAMESPACE/webserver
  OC_VERSION: 1.3.3
  YARN_CACHE: .yarn

test:
  stage: build
  image: node:$NODE_VERSION
  script:
    # install necessary application packages
    - yarn install --cache-folder="$YARN_CACHE"
    # test the application sources
    - yarn test
  cache:
    key: $CI_PROJECT_ID
    paths:
      - $YARN_CACHE
      - node_modules
  # TODO: remove once issue is fixed
  allow_failure: true

mirror:
  stage: build
  image: samueldebruyn/debian-git:latest
  script:
    # mirror the repository to GitHub
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git remote add github git@github.com:appuio/shop-example-webserver.git
    - ssh-agent bash -c 'ssh-add <(echo "$DEPLOY_KEY"); git push github master'
  allow_failure: true

compile:
  stage: build
  image: node:$NODE_VERSION
  script:
    # install necessary application packages
    - yarn install --cache-folder="$YARN_CACHE"
    # build the application sources
    - yarn build
  artifacts:
    expire_in: 5min
    paths:
      - build
  cache:
    key: $CI_PROJECT_ID
    paths:
      - $YARN_CACHE
      - node_modules
  only:
    - master
    - tags

build-staging:
  environment: webserver-staging
  stage: deploy-staging
  image: appuio/gitlab-runner-oc:$OC_VERSION
  services:
    - docker:dind
  script:
    # login to the service account to get access to the internal registry
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    - docker login -u serviceaccount -p `oc whoami -t` $OC_REGISTRY_URL
    # build the docker image and tag it as latest
    # use the current latest image as a caching source
    - docker pull $OC_REGISTRY_IMAGE:latest
    - docker build --cache-from $OC_REGISTRY_IMAGE:latest -t $OC_REGISTRY_IMAGE:latest .
    # update the configuration in OpenShift
    - oc replace -f docker/openshift -R
    # push the image to the internal registry
    - docker push $OC_REGISTRY_IMAGE:latest
    # trigger a deployment
    - oc deploy webserver-staging --latest --follow
  only:
    - master
  except:
    - tags
  tags:
    - dockerbuild

build-preprod:
  environment: webserver-preprod
  stage: deploy-preprod
  image: appuio/gitlab-runner-oc:$OC_VERSION
  services:
    - docker:dind
  script:
    # login to the service account to get access to the internal registry
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    - docker login -u serviceaccount -p `oc whoami -t` $OC_REGISTRY_URL
    # build the docker image and tag it as stable
    # use the current latest image as a caching source
    - docker pull $OC_REGISTRY_IMAGE:latest
    - docker build --cache-from $OC_REGISTRY_IMAGE:latest -t $OC_REGISTRY_IMAGE:stable .
    # update the configuration in OpenShift
    - sed -i 's;webserver-staging;webserver-preprod;g' docker/openshift/*
    - sed -i 's;webserver:latest;webserver:stable;g' docker/openshift/*
    - sed -i 's;'$CLUSTER_IP_STAGING';'$CLUSTER_IP_PREPROD';g' docker/openshift/*
    - oc replace -f docker/openshift -R
    # push the image to the internal registry
    - docker push $OC_REGISTRY_IMAGE:stable
    # trigger a deployment
    - oc deploy webserver-preprod --latest --follow
  only:
    - tags
  tags:
    - dockerbuild

build-prod:
  environment: webserver-prod
  stage: deploy-prod
  image: appuio/gitlab-runner-oc:$OC_VERSION
  script:
    # login to the service account to get access to the CLI
    - oc login $KUBE_URL --token=$KUBE_TOKEN
    # update the configuration in OpenShift
    - sed -i 's;webserver-staging;webserver-prod;g' docker/openshift/*
    - sed -i 's;webserver:latest;webserver:live;g' docker/openshift/*
    - sed -i 's;'$CLUSTER_IP_STAGING';'$CLUSTER_IP_PROD';g' docker/openshift/*
    - oc replace -f docker/openshift -R
    # tag the current stable image as live
    - oc tag webserver:stable webserver:live
    # trigger a deployment
    - oc deploy webserver-prod --latest --follow
  only:
    - tags
  when: manual
