stages:
    - test
    - compile
    - build

test:
    stage: test
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-dir=".yarn-cache"
        - yarn test
    artifacts:
        expire_in: "5min"
        paths:
            - ".yarn-cache"
    cache:
        paths:
            - ".yarn-cache"

compile:
    stage: compile
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-dir=".yarn-cache"
        - yarn build
    artifacts:
        expire_in: "5min"
        paths:
            - "build"

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE
    tags:
        - dockerbuild