stages:
    - build
    - deploy
    - deploy-prod

cache:
    key: "$CI_PROJECT_ID"
    paths:
        - .yarn
        - node_modules/

test:
    stage: build
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-folder=".yarn"
        # - yarn test

compile:
    stage: build
    image: registry.vshn.net/roland.schlaefli/docs_runner_yarn2
    script:
        - yarn install --cache-folder=".yarn"
        - yarn build
    artifacts:
        expire_in: "5min"
        paths:
            - "build"
    only:
        - master
        - tags

build-dev:
    stage: deploy
    image: registry.vshn.net/roland.schlaefli/docs_runner_oc
    services:
        - docker:dind
    script:
        - oc login $KUBE_URL --token=$KUBE_TOKEN
        - docker login -u serviceaccount -p `oc whoami -t` $OC_REGISTRY_URL
        - docker pull $OC_REGISTRY_IMAGE:latest
        - docker build --cache-from $OC_REGISTRY_IMAGE:latest -t $OC_REGISTRY_IMAGE:latest .
        - docker push $OC_REGISTRY_IMAGE:latest
    only:
        - master
    except:
        - tags
    tags:
        - dockerbuild
    variables:
        OC_REGISTRY_URL: "registry.appuio.ch"
        OC_REGISTRY_IMAGE: "$OC_REGISTRY_URL/$KUBE_NAMESPACE/docs_example_webserver"
    environment: dev

build-preprod:
    stage: deploy
    image: registry.vshn.net/roland.schlaefli/docs_runner_oc
    services:
        - docker:dind
    script:
        - oc login $KUBE_URL --token=$KUBE_TOKEN
        - docker login -u serviceaccount -p `oc whoami -t` $OC_REGISTRY_URL
        # - docker pull $OC_REGISTRY_IMAGE:stable
        - docker build --cache-from $OC_REGISTRY_IMAGE:stable -t $OC_REGISTRY_IMAGE:stable .
        - docker push $OC_REGISTRY_IMAGE:stable
    only:
        - tags
    tags:
        - dockerbuild
    variables:
        OC_REGISTRY_URL: "registry.appuio.ch"
        OC_REGISTRY_IMAGE: "$OC_REGISTRY_URL/$KUBE_NAMESPACE/docs_example_webserver"
    environment: preprod

build-prod:
    stage: deploy-prod
    image: registry.vshn.net/roland.schlaefli/docs_runner_oc
    script:
        - oc login $KUBE_URL --token=$KUBE_TOKEN
        - oc deploy webserver --latest --follow
    only:
        - tags
    when: manual
    environment: prod

